챌린지 API 인가 로직 추가
2-Docthru-team1/2-Docthru-team1-BE pull request #123
Opened 2024-11-21 18:50 UTC by alscksdlek

## 이슈 번호
- close #118

## 작업 사항 설명
- 챌린지 API 인가 로직 추가
- 
## 작업 사항
- [x] 로그인한 유저만 챌린지 생성(신청) 가능
- [x] 챌린지 정보 수정시 requestUserId와 챌린지를 수정을 요청한 사람의 id 확인
- [x] 챌린지 상태 수정은 수정을 요청한 사람의 role이 admin인지 확인

## 기타
1. 토큰 있을 때 post 가능 테스트
2. 토큰 없을 때 post 오류 테스트
3. userId 잘못됐을 때 patch 오류 테스트
4. admin일때만 상태 변경 가능 테스트
5. normal 일 때 status canceled 변경 가능 테스트
6. admin이 거절할 때 admin 누락 오류 테스트 

이렇게 테스트 진행했습니다 이미지는 너무 많아서 첨부하지 않겠습니다!

2024-11-21 23:59 UTC, csbizz requested changes
challenge에서 인증/인가 관련기능은 미들웨어를 이용해서 처리할 수 있으니 따로 ChallengeAuth층을 만들지 않고 challenge 계층에서 처리하면 될 것 같습니다.
코드 자체는 커스텀 에러를 던지지 않는 부분을 제외하면 문제 없어보입니다!

2024-11-22 00:07 UTC, taeyeonkim94 approved these changes

2024-11-22 00:27 UTC, alscksdlek commented
> challenge에서 인증/인가 관련기능은 미들웨어를 이용해서 처리할 수 있으니 따로 ChallengeAuth층을 만들지 않고 challenge 계층에서 처리하면 될 것 같습니다. 코드 자체는 커스텀 에러를 던지지 않는 부분을 제외하면 문제 없어보입니다!

제 코드 보시면 challengeAuth에서 challengeRepository를 가져와서 쓰고 있습니다 인스턴스를 하나 더 생성하기 않기 위해서 계층을 하나 더 만들었는데 다른 방법이 있을까요?-?

2024-11-22 04:36 UTC, alscksdlek commented
> challenge에서 인증/인가 관련기능은 미들웨어를 이용해서 처리할 수 있으니 따로 ChallengeAuth층을 만들지 않고 challenge 계층에서 처리하면 될 것 같습니다. 코드 자체는 커스텀 에러를 던지지 않는 부분을 제외하면 문제 없어보입니다!

서비스 단에서 처리하게 수정하였습니다!

2024-11-22 05:32 UTC, csbizz approved these changes
LGTM

2024-11-22 05:56 UTC, merged