✨ Feat #101 챌린지 작업물 post api 구현
2-Docthru-team1/2-Docthru-team1-BE pull request #135
Opened 2024-11-22 07:34 UTC by taeyeonkim94

챌린지 작업물 post api 구현 및 get 메소드들의 리스폰스에 이미지워크의 url 필드를 제외한 필드 필터링 수정

## 이슈 번호

- close #101 

## 작업 사항 설명
챌린지 작업물 post api 구현 현재는 들어오는 string을 그대로 저장-> 업로드 구현X'
get 메소드 2개 리스폰스에 워크이미지 모델의 url만 내보내도록 수정
## 작업 사항

- [x] 작업물 post api 구현
- [x] get 메소드 response 수정

## 기타
포스트 결과 이미지
![포스트결과이미지](https://github.com/user-attachments/assets/1fe247b1-7a38-4210-a7ea-bd701874b65a)

겟  결과 이미지
![겟이미지1](https://github.com/user-attachments/assets/e7330391-c47a-47e8-95b0-b786fd272f38)
![겟이미지2](https://github.com/user-attachments/assets/3e3ec7e3-1c7b-4d50-9602-3f7da2e10484)
ithub.com/user-attachments/assets/ea4d0086-6290-4e49-bb1f-0fe1753b0f8f)

2024-11-22 07:44 UTC, alscksdlek approved these changes

2024-11-22 08:15 UTC, csbizz requested changes

2024-11-22 08:15 UTC, csbizz commented on package.json
> +    "multer": "^1.4.5-lts.1",
사용하지 않은 패키지 같습니다

2024-11-22 08:15 UTC, csbizz commented on src/controllers/work.controller.ts
> +//import type { Request } from '#types/common.types.js';
같은 줄이 주석으로 하나 더 있네요

2024-11-22 08:15 UTC, csbizz commented on src/repositories/work.repository.ts
> +        owner: { connect: { id: ownerId } },
민선님께도 말씀드린 적 있지만 prisma에선 `challenge: challengeId`처럼 FK를 제대로 입력만 해주면 추론해서 관계를 연결해줍니다.
물론 이렇게 명시적으로 연결을 만드는 것도 의미가 명확해진다는 의미에서 좋은 습관이라고 생각합니다.

2024-11-22 08:15 UTC, csbizz commented on src/routes/challenge.route.ts
> +  .post(tokenVerifier.optionalVerifyAccessToken, validateCreateChallenge, challengeController.postChallenge);
challege를 생성하는 것은 accessToken(유저 정보)을 반드시 요구하는 작업입니다. optional하지 않으니 verifyAccessToken을 쓰는게 더 적절해보입니다.

2024-11-22 08:15 UTC, csbizz commented on src/routes/challenge.route.ts
> +challengeRouter.patch('/:id/status', tokenVerifier.optionalVerifyAccessToken, challengeController.patchChallengeStatus);
여기도 위와 마찬가지입니다.

2024-11-22 08:15 UTC, csbizz commented on src/routes/challenge.route.ts
> +  .post(tokenVerifier.optionalVerifyAccessToken, workController.postWork);
여기도 마찬가지

2024-11-22 08:25 UTC, taeyeonkim94 commented on package.json
> +    "multer": "^1.4.5-lts.1",
multer로 받을 생각이였어서 설치했던고 같아요 수정해서 올리겠습니다

2024-11-22 08:25 UTC, taeyeonkim94 commented on src/controllers/work.controller.ts
> +//import type { Request } from '#types/common.types.js';
삭제하겠습니다

2024-11-22 13:02 UTC, taeyeonkim94 commented on src/routes/challenge.route.ts
> +  .post(tokenVerifier.optionalVerifyAccessToken, validateCreateChallenge, challengeController.postChallenge);
수정완

2024-11-22 13:02 UTC, taeyeonkim94 commented on src/routes/challenge.route.ts
> +challengeRouter.patch('/:id/status', tokenVerifier.optionalVerifyAccessToken, challengeController.patchChallengeStatus);
수정완

2024-11-22 14:56 UTC, taeyeonkim94 commented on src/routes/challenge.route.ts
> +  .post(tokenVerifier.optionalVerifyAccessToken, workController.postWork);
수정완

2024-11-23 10:56 UTC, csbizz approved these changes

2024-11-23 11:50 UTC, merged