Feat/#136 work patch and delete api
2-Docthru-team1/2-Docthru-team1-BE pull request #140
Opened 2024-11-23 06:10 UTC by taeyeonkim94

## 이슈 번호

- close #136 

## 작업 사항 설명

## 작업 사항

- [x] 챌린지 작업물 수정기능 구현
- [x] 챌린지 작업물 삭제 기능 구현
## 기타
![수정결과](https://github.com/user-attachments/assets/45369293-f3c4-4982-82de-77f788d4907f)

![삭제결과](https://github.com/user-attachments/assets/9068dd36-2e1c-46d7-ba34-919fbc2e0d97)

2024-11-23 11:07 UTC, csbizz requested changes

2024-11-23 11:07 UTC, csbizz commented on src/controllers/work.controller.ts
> +    assert(workData, CreateWork, MESSAGES.WRONG_FORMAT);
검증하는 코드가 더 위로 가야할 것 같습니다!

2024-11-23 11:07 UTC, csbizz commented on src/controllers/work.controller.ts
> +    res.sendStatus(204);
삭제시 삭제된 논리삭제 레코드를 200과 함께 보내주시면 됩니다

2024-11-23 12:39 UTC, taeyeonkim94 commented on src/controllers/work.controller.ts
> +    assert(workData, CreateWork, MESSAGES.WRONG_FORMAT);
수정 완

2024-11-23 12:39 UTC, taeyeonkim94 commented on src/controllers/work.controller.ts
> +    res.sendStatus(204);
수정완

2024-11-24 05:38 UTC, csbizz reviewed
충돌 수정 후 푸시 해주시면 승인 하겠습니다.

2024-11-24 05:51 UTC, alscksdlek approved these changes

2024-11-24 07:10 UTC, csbizz approved these changes

2024-11-24 07:16 UTC, MCprotein commented on src/repositories/work.repository.ts
> +      await Promise.all(existingWorkImages.map(workImage => this.workImage.delete({ where: { id: workImage.id } })));
@taeyeonkim94 태연님! https://www.prisma.io/docs/orm/reference/prisma-client-reference#log 이거처럼 deleteMany 쓰면 안되나요??

2024-11-24 07:49 UTC, taeyeonkim94 commented on src/repositories/work.repository.ts
> +      await Promise.all(existingWorkImages.map(workImage => this.workImage.delete({ where: { id: workImage.id } })));
workId로 필터를해서 연결된 workImage 모델들을 모두 삭제했습니다

2024-11-24 08:00 UTC, csbizz approved these changes

2024-11-24 08:02 UTC, merged