이달의 챌린지 get api 생성
2-Docthru-team1/2-Docthru-team1-BE pull request #186
Opened 2024-11-27 16:14 UTC by alscksdlek

## 이슈 번호
- close #184

## 작업 사항 설명
이달의 챌린지 get api 생성

## 작업 사항
- [x] 이달의 챌린지 mock 데이터 데이터베이스에 추가
- [x] 이달의 챌린지 get api 생성

## 기타

![실행](https://github.com/user-attachments/assets/382059d2-b467-4136-a7f9-55b12b5debbf)

2024-11-27 16:24 UTC, taeyeonkim94 requested changes

2024-11-27 16:24 UTC, taeyeonkim94 commented on src/repositories/challenge.repository.ts
> +  findMonthlyChallenge = async (): Promise<Challenge[] | null> => {
findMany를 공유하는게 좋지 않을까요?

2024-11-27 16:28 UTC, csbizz approved these changes

2024-11-27 16:31 UTC, taeyeonkim94 requested changes

2024-11-27 16:31 UTC, taeyeonkim94 commented on prisma/mock/challengeMock.ts
> +    monthly: true,
monthly를 달로 하는게 좋지 않을까요?

2024-11-28 00:01 UTC, taeyeonkim94 approved these changes

2024-11-28 00:33 UTC, taeyeonkim94 requested changes

2024-11-28 00:33 UTC, taeyeonkim94 commented on src/repositories/challenge.repository.ts
> +        ...(option.monthly ? { monthly: option.monthly } : {}),
이거 이달의 챌린지 전용 findMany인데 삼항 연산자로 값이 없으면 필터 없이 모두 나오면 안될거 같아요
이 상태로면 mothly 값이 없으면 이달의 챌린지 뿐만 아니라 모든 챌린지가 나올거 같은데요?
제 생각에는 애초에 컨트롤러에서 값이 없으면 애초에 오류를 발생시키던가 현재 날짜 찍어서 달부분을 기본값으로 찍어줘야 할거 같아요

2024-11-28 01:13 UTC, taeyeonkim94 requested changes

2024-11-28 01:13 UTC, taeyeonkim94 commented on src/repositories/challenge.repository.ts
> +          gte: new Date(`${currentYear}-01-01T00:00:00Z`),
수정 안하셔도 돼요

2024-11-28 01:13 UTC, taeyeonkim94 commented on prisma/mock/challengeMock.ts
> +    createdAt: new Date('2024-11-17T10:00:00.000Z'),
목데이터 넘버랑 이름이 겹칠거같아서 수정 부탁드려요

2024-11-28 05:02 UTC, alscksdlek commented on prisma/mock/challengeMock.ts
> +    createdAt: new Date('2024-11-17T10:00:00.000Z'),
네 충돌이 일어났네요 수정하겠습니다!

2024-11-28 05:06 UTC, alscksdlek commented on src/repositories/challenge.repository.ts
> +        ...(option.monthly ? { monthly: option.monthly } : {}),
```

2024-11-28 05:11 UTC, alscksdlek commented on src/repositories/challenge.repository.ts
> +          gte: new Date(`${currentYear}-01-01T00:00:00Z`),
이전년도의 챌린지를 보여주는 개념이 저희 계획에는 아예 없으니깐 이번 년도로 요구사항이 고정되어있어 문제가 되지 않는다고 생각하고 동적으로 연도를 조정하고 싶으면 서비스 단에 currentYear을 수정하는 방식으로 가능합니다! 저는 요구사항에 맞는 코드가 단순한 방법을 더 좋아해서 저렇게 작성한 것 같아요!

2024-11-28 05:14 UTC, alscksdlek commented on src/services/challenge.service.ts
> +    const monthlyChallenge = await this.challengeRepository.findMonthlyChallenge({ monthly: validMonthly }, currentYear);
유효성 검증은 서비스로 알고있습니다! 컨트롤러는 클라이언트랑 요청을 받고 응답만 하는 역할이라고 생각해서요

2024-11-28 05:26 UTC, csbizz approved these changes

2024-11-28 05:35 UTC, taeyeonkim94 approved these changes

2024-11-28 05:35 UTC, merged