Feat/#27 get by id challenge
2-Docthru-team1/2-Docthru-team1-BE pull request #35
Opened 2024-11-17 20:20 UTC by alscksdlek

## 이슈 번호
close #27 

## 작업 사항

- [x] getChallengeById api 구현
- [x] mock, seed 파일 추가해서 테스트

## 기타
![image](https://github.com/user-attachments/assets/d60d5c4f-4dc7-410f-a47a-4f29b8f6d8de)

2024-11-17 23:05 UTC, csbizz commented on src/middlewares/errorCatchHandler.ts
> +export function errorCatchHandler(handler: (req: Request, res: Response, next: NextFunction) => Promise<any>) {
마찬가지로 any 타입은 피해주세요!

2024-11-17 23:05 UTC, csbizz commented on src/routes/challenge.route.ts
> +challengeRouter.route('/:id').get(errorCatchHandler(challengeController.getChallengeById));
async 핸들러 형식으로 실제 error handler로 넘겨주는 코드인 것 같은데 맞나요?
일반적으로 권장되는 형식이지만, 저희는 express-async-errors라는 라이브러리를 사용 중입니다. 따로 async handler를 사용하지 않아도 throw된 error는 next에 담겨서 에러 핸들러로 전달됩니다!

2024-11-18 05:53 UTC, csbizz approved these changes

2024-11-18 05:55 UTC, csbizz requested changes
승인 실수;

2024-11-18 07:31 UTC, taeyeonkim94 commented on prisma/mock/challengeMock.ts
> +    id: '029dc2ea-93d1-4c8d-844e-07fd9c87d23e',
이건 저랑 상의했던 부분이기도 한데 저희가 유저 기능은 아니지만 유저 데이터가 있는 상태로 구현하기 위해서 유저쪽에서 변경이 되더라도 손 쓰기 쉽게 임시로 하나만 생성했습니다

2024-11-18 13:19 UTC, alscksdlek commented on prisma/schema.prisma
> +  requests      Challenge[]     @relation(name: "requests")
네 까먹고 안했네요 필드 이름이 아니라 name: "requests" 이 부분에서만 오타가 있었어서 마이그레이션 없이도 테스트가 잘 진행됐던 것 같습니다!

2024-11-18 13:28 UTC, alscksdlek commented on src/routes/challenge.route.ts
> +challengeRouter.route('/:id').get(errorCatchHandler(challengeController.getChallengeById));
네 맞습니다 express-async-errors 라이브러리를 사용하는지 몰라서 작성했었습니다 express-async-errors 라이브러리를 사용하게 수정하였습니다!

2024-11-18 13:33 UTC, alscksdlek commented on src/controllers/challenge.controller.ts
> +    }
해당 코드 삭제해 express-async-errors 라이브러리 사용하게 했습니다!

2024-11-18 13:42 UTC, alscksdlek commented on src/controllers/challenge.controller.ts
> +  getChallengeById = async (req: Request, res: Response): Promise<any> => {
자동 추론하게 바꿨습니다!

2024-11-18 13:47 UTC, alscksdlek commented on prisma/seed.ts
> +  }
```
requests      Challenge[]     @relation(name: "requests")
  participation Challenge[]     @relation(name: "participation")
  ownWorks      ChallengeWork[] @relation(name: "ownership")
  likeWorks     ChallengeWork[] @relation(name: "likeRelation")
  Feedback      Feedback[]
  abortReasons  AbortReason[]
  Challenge     Challenge[] 
```
이거 다 외래 키 아닌가요?

2024-11-18 13:49 UTC, alscksdlek commented on prisma/seed.ts
> +  }
```
  for (const user of USERS) {
    await prisma.user.create({
      data: {
        id: user.id,
        createdAt: user.createdAt,
        updatedAt: user.updatedAt,
        deleteAt: user.deleteAt,
        name: user.name,
        email: user.email,
        password: user.password,
        refreshToken: user.refreshToken,
        role: user.role,
      },
    });
  }
```
이 부분에서 requests 연결을 안해줘서 추가한거예요 seed 파일에 대해서는 시간이 될 때 얘기를 좀 더 해봐야 할 것 같습니다!

2024-11-18 13:54 UTC, csbizz commented on prisma/seed.ts
> +  }
해당 관계들은 User가 아니라 반대쪽에 FK가 설정되는 경우입니다!
Prisma schema상 Model[] 형식이라면 반대쪽 모델에 FK가 설정되고, 서로가 Model[] 관계라면 프리즈마가 익명의 정션 테이블을 만들어서 관리해줍니다!

2024-11-18 14:04 UTC, csbizz approved these changes

2024-11-18 16:14 UTC, taeyeonkim94 approved these changes

2024-11-19 00:50 UTC, merged