레시피 API 구현
2-Docthru-team1/2-Docthru-team1-BE pull request #47
Opened 2024-11-18 12:37 UTC by ganghoho

## 이슈 번호

- close #19 

## 작업 사항

- [x]  콜백을 controller, service, repository 등의 파일을 참고해서 계층에 맞게 수정
- [x] 변수명 리뷰 반영하여 변경
- [x] 에러메세지 utils 디렉토리 안에 constants 디렉토리에 enum으로 관리 반영, 한글 메세지 반영

2024-11-18 12:52 UTC, csbizz requested changes
프로젝트 내부 다른 파일들 참조하셔서 형식 지켜서 작성해주시면 좋겠습니다!
가능하다면 interface 작성도 해주시면 좋겠지만 필요하다면 후에 제가 작성하도록 하겠습니다

2024-11-18 12:52 UTC, csbizz commented on src/controllers/recipe.controller.ts
> +import { ErrorMessages } from '../utils/constants/recipeErrorMessages.js';
커스텀 경로가 아니라 상대경로가 지정됐네요
혹시 직접 import하신건가요? 아니면 vscode의 제안을 통해서 import하신 건가요?

2024-11-18 12:52 UTC, csbizz commented on src/controllers/recipe.controller.ts
> +    }
에러 핸들링을 위해 try catch 구문을 사용하는 습관은 매우 좋습니다!
하지만 express는 error handler를 따로 설정하고, 해당 핸들러로 error를 넘겨주는 방식으로 에러 핸들링을 진행하는 것이 좋습니다.
또한 저희 프로젝트에는 express-async-errors라는 라이브러리가 있어서 try catch 구문을 사용하지 않아도 throw error하면 error handler에게 에러가 전달됩니다!

2024-11-18 12:52 UTC, csbizz commented on src/routes/recipe.route.ts
> +  try {
router에선 controller의 메소드를 호출하기만 합니다. 여기에 로직 코드를 삽입하지 말아주세요.

2024-11-18 12:52 UTC, csbizz commented on src/controllers/recipe.controller.ts
> +class RecipeController {
service 연결이 안되어있네요. 다른 파일들 확인하시고 형식 지켜주시기 바랍니다.

2024-11-18 12:52 UTC, csbizz commented on src/repositories/recipe.repositories.ts
> +class RecipeRepository {
컨트롤러와 마찬가지로 형식 지켜주시기 바랍니다

2024-11-18 12:52 UTC, csbizz commented on src/services/recipe.service.ts
> +class RecipeService {
여기도 형식 지켜주시면 좋겠습니다

2024-11-18 12:52 UTC, csbizz commented on src/utils/constants/recipeErrorMessages.ts
> +}
constants에 messages 파일이 있었을텐데 따로 작성하신 이유가 있나요?

2024-11-18 12:52 UTC, csbizz commented on src/services/recipe.service.ts
> +    return await RecipeRepository.getRecipes(skip, limit);
리스트를 조회하는 경우, 페이지네이션을 위해 전체 count도 함께 보내야 합니다.

2024-11-18 16:11 UTC, taeyeonkim94 requested changes

2024-11-18 16:11 UTC, taeyeonkim94 commented on src/routes/recipe.route.ts
> +    const pageNumber = parseInt(page as string, 10);
parseInt 변환하셨는데 변수명은 pageNumber입니다 limit도 동일해요

2024-11-19 07:59 UTC, csbizz requested changes
수정사항 적용 후에 해당하는 코멘트에 수정사항에 대해 남겨주세요.
해당 문제가 해결됐는지 여부를 리뷰어가 확인할 수 없습니다.

2024-11-19 07:59 UTC, csbizz commented on src/app.ts
app.ts에는 따로 변경이 있었기 때문에 수정하지 않으셔도 됩니다.

2024-11-19 07:59 UTC, csbizz commented on src/containers/recipe.container.ts
> +const recipeRepository = new RecipeRepository();
prisma Client와 연결하는 부분이 빠졌습니다.

2024-11-19 07:59 UTC, csbizz commented on src/controllers/recipe.controller.ts
> +
최신화된 형식하고 다르네요... 일단 이번엔 넘기신 뒤, 다음 작업하실 때 dev에서 pull 해오신 뒤에 형식 보고 수정해주세요.

2024-11-19 07:59 UTC, csbizz commented on src/repositories/recipe.repositories.ts
> +  }
여기 생성자는 왜 비어있나요?

2024-11-19 07:59 UTC, csbizz commented on src/services/recipe.service.ts
> +    return { recipes, totalCount };
내보내는 양식 api 명세서 확인 후에 맞춰주세요

2024-11-19 09:05 UTC, ganghoho commented on src/containers/recipe.container.ts
> +const recipeRepository = new RecipeRepository();
추가했습니다!

2024-11-19 09:06 UTC, ganghoho commented on src/controllers/recipe.controller.ts
> +      const { page = '1', limit = '10' } = req.query;
음 일단 해보긴 했는데 의도한 바인지 모르겠습니다

2024-11-19 09:09 UTC, ganghoho commented on src/controllers/recipe.controller.ts
> +
적용해봤습니다

2024-11-19 09:09 UTC, ganghoho commented on src/services/recipe.service.ts
> +    return { recipes, totalCount };
완료했습니다

2024-11-19 09:20 UTC, taeyeonkim94 requested changes

2024-11-19 09:20 UTC, taeyeonkim94 commented on src/controllers/recipe.controller.ts
> +      const recipes = await this.recipeService.getRecipes(pageInt, limitInt, sortBy as string, order as string, categoryEnum);
sortBy와 order도 enum으로 관리하는게 더 좋아보여요

2024-11-19 09:20 UTC, taeyeonkim94 commented on src/services/recipe.service.ts
> +  async getRecipes(page: number, limit: number, sortBy: string = 'likes', order: string = 'asc', category?: Category) {
기본값 지정은 컨트롤러에서 끝내야 한다고 생각해요
뒤의 서비스나 리포지토리에서는 받아온 값을 쓰기만 하면 될거같아요
혹시 문제가 생긴다면 알려주세요

2024-11-19 09:21 UTC, csbizz commented on src/repositories/recipe.repositories.ts
> +  }
prismaClient를 받아오는 부분은 잘 작성하신 것 같습니다.
다음부터는 여기에 this.recipe = prisma.recipe 이런식으로 model을 직접 연결해주세요.

2024-11-19 09:28 UTC, taeyeonkim94 requested changes

2024-11-19 09:28 UTC, taeyeonkim94 commented on src/services/recipe.service.ts
> +  async getRecipes(page: number, limit: number, sortBy: string = 'likes', order: string = 'asc', category?: Category) {
근데 왜 order의 기본값이 asc인가요?

2024-11-19 09:28 UTC, taeyeonkim94 commented on src/controllers/recipe.controller.ts
> +      const { page = '1', limit = '10', category, sortBy = 'likes', order = 'asc' } = req.query;
order의 기본값이 왜 'asc'인가요?

2024-11-19 10:13 UTC, ganghoho commented on src/controllers/recipe.controller.ts
> +      const recipes = await this.recipeService.getRecipes(pageInt, limitInt, sortBy as string, order as string, categoryEnum);
적용했습니다

2024-11-19 10:14 UTC, ganghoho commented on src/repositories/recipe.repositories.ts
> +  }
네 알겠습니다!

2024-11-19 10:15 UTC, ganghoho commented on src/services/recipe.service.ts
> +  async getRecipes(page: number, limit: number, sortBy: string = 'likes', order: string = 'asc', category?: Category) {
일단 완료했는데 우선 기본값은 asc에서 바꾸진 않았습니다 추후에 필요시 바꾸도록 하겠습니다

2024-11-20 05:04 UTC, ganghoho commented on src/app.ts
> +>>>>>>> d7732ca8d98ebc4b8308e912ae4a88687bf2a590
수정했습니다!

2024-11-20 05:05 UTC, ganghoho commented on src/controllers/recipe.controller.ts
> +      }
에러핸들러 넣었습니다!

2024-11-20 05:06 UTC, csbizz commented on src/utils/validators/pagination.ts
> +    limitInt: isNaN(limitInt) || limitInt < 1 ? 10 : limitInt,
pageInt나 limitInt가 NaN이면 리턴시 true가 리턴될겁니다.

2024-11-20 06:22 UTC, csbizz approved these changes

2024-11-20 06:22 UTC, csbizz commented on src/utils/validators/pagination.ts
> +    limitInt: Number.isNaN(limitInt) || limitInt < 1 ? 10 : limitInt,
여전히 isNan일 경우 true가 반환됩니다.

2024-11-20 06:41 UTC, taeyeonkim94 requested changes

2024-11-20 06:41 UTC, taeyeonkim94 commented on src/routes/recipe.route.ts
> +router.get('/recipes', recipeController.getRecipes);
레시피 라우터는 app.ts 파일에서 '/recipes' 경로를 가지고 레시피 라우터 안에서는 그 이후의 경로를 가집니다 수정 부탁드려요

2024-11-20 06:41 UTC, taeyeonkim94 commented on src/controllers/recipe.controller.ts
> +      const { page = '1', limit = '10', category, sortBy = SortBy.LIKES, order = Order.latestFirst } = req.query;
order와 검색어는 다르게 다뤄줘야 될거 같아요 현재 order에 통합되어 있는거 같은데
피그마상으로는 검색과 정렬은 분리되어 있는거 같아요

2024-11-20 06:41 UTC, taeyeonkim94 commented on src/controllers/recipe.controller.ts
> +      res.status(200).json(recipes);
status 없이 json만 보내도 200이 도착하는걸로 알고 있어요 일관성을 위해서라면 유지하셔도 됩니다

2024-11-20 06:41 UTC, taeyeonkim94 commented on src/utils/constants/enum.ts
> +  TITLE = 'title',
title이 여기서 가지면 안될거같아요 좋아요순, 생성순 vs 검색
검색은 좋아요순과 생성순가 별개로 같이 적용될 수 있어야 합니다
그리고 검색은 보통 제목뿐만이 아니라 본문 내용도 포함하게 해야되니까 이름이 타이틀보단 키워드가 맞겠네요

2024-11-20 06:41 UTC, taeyeonkim94 commented on src/repositories/recipe.repositories.ts
> +        [sortBy]: order,
검색부분 적용 필요합니다

2024-11-21 04:47 UTC, closed without merging